# Generated by Django 5.1 on 2024-10-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_profile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ace',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='goals_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='longuest_exchange',
            field=models.IntegerField(default=0),
        ),
    ]
