# Generated by Django 5.1 on 2024-11-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0007_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='anonymized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='deletion_requested',
            field=models.BooleanField(default=False),
        ),
    ]
