# Generated by Django 5.1 on 2024-11-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0009_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/pepe.jpg', upload_to='profile_pictures/'),
        ),
    ]
