# Generated by Django 5.1 on 2024-11-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0013_profile_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='pong.profile'),
        ),
    ]
