# Generated by Django 5.1 on 2024-12-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0014_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='player2_nickname',
            field=models.CharField(default='Unknown', max_length=15),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_nickname',
            field=models.CharField(default='Unknown', max_length=15),
        ),
    ]
