# Generated by Django 5.1 on 2024-12-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0015_remove_match_player2_remove_match_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ace',
            field=models.IntegerField(default='0', max_length=15),
        ),
    ]
