# Generated by Django 5.1 on 2024-12-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0016_match_ace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='ace',
            field=models.IntegerField(default='0'),
        ),
    ]
