# Generated by Django 5.1 on 2024-12-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0017_alter_match_ace'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='duration',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_time_in_game',
            field=models.FloatField(default=0),
        ),
    ]
